### ISSUE TITLE
Add support for MP modules as dependencies for Android target

### ISSUE THREAD

**Issue by arnis71** [korlibs/korge-plugins#16]
I am trying to make a simple game with Korge but I ran into a problem where I can not build for Android target when my game module game depends on another multiplatform module data. Take a look here https://github.com/arnis71/SpaceGame.

It has one data class that I want to use on the backend and in the game called Projectile. It sees this class in game module in IDE and even runs the jvm target. But when I try to start it on android emulator it fails at :android:compileDebugKotlin and says that it can not find this Projectile class.

Possible solution is to include all dependency modules sources to generated build.gradle

**Comment by arnis71** [comment]
Found a solution with gradle. It is not hacky and should work as expected. Will push PR tomorrow.

**Comment by soywiz** [comment]
Nice! Thanks :+1:

**Comment by arnis71** [comment]
Submitted PR https://github.com/korlibs/korge-plugins/pull/18
