### ISSUE TITLE
Can't build iOS target due to absence of resources folder

### ISSUE THREAD

**Issue by arnis71** [korlibs/korge-plugins#19]
When building iOS target build fails with 
`error: /../build/combinedResources/resources: No such file or directory (in target 'app-Arm64-Debug' from project 'app')`
or more precisely `The following build commands failed: PBXCp /../build/combinedResources/resources /../build/platforms/ios/app.xcodeproj/build/Build/Products/Debug-iphoneos/unnamed.app/include/app/resources`

This is due to 
```
doFirst {
	combinedResourcesFolder.mkdirs()
}
```
not being triggered in `copyIosResources` task. Moving folder creation to configuration stage does not help as gradle marks this directory as stale and deletes it before the PBXCp runs.

**Comment by soywiz** [comment]
Should be fixed since 2.1.1.3
