### ISSUE TITLE
Read local.properties to get sdk.dir

### ISSUE THREAD

**Issue by soywiz** [korlibs/korge-plugins#22]
Here: https://github.com/korlibs/korge-plugins/blob/738bfea7d4c72fb1716fb56bdce9f0fa170e9283/korge-gradle-plugin/src/main/kotlin/com/soywiz/korge/gradle/targets/android/Android.kt#L18-L29

**Comment by RezMike** [comment]
The line in `local.properties` added by Android Studio:
```
sdk.dir=C\:\\Android\\sdk
```
