### ISSUE TITLE
More than one file was found with OS independent path 'META-INF/AL2.0'

### ISSUE THREAD

**Issue by yvolk** [korlibs/korge-plugins#26]
https://github.com/korlibs/korge-plugins/blob/47a64b90263f6cad967634cc5d24a11a1596ce4e/korge-gradle-plugin/src/main/kotlin/com/soywiz/korge/gradle/targets/android/Android.kt#L178

The packagingOptions here misses at least 

    it.exclude("META-INF/AL2.0")
    it.exclude("META-INF/LGPL*")

Please note that these lines (and some other excludes) are present in korge-next in

korge-gradle-plugin/src/main/kotlin/com/soywiz/korge/gradle/KorgeGradlePluginAndroid.kt

**Comment by soywiz** [comment]
Added on 2.0.0.2-rc2 : https://github.com/korlibs/korge-plugins/releases/tag/v2.0.0.2-rc2

**Comment by yvolk** [comment]
@soywiz Thank you, it works now!
