### ISSUE TITLE
cannot build android aar project from scratch because no local.properties existence

### ISSUE THREAD

**Issue by pablocaviglia-uy** [korlibs/korge-plugins#28]
**OS**: Mac
**Android SDK location on local.properties**: sdk.dir=/Users/pablocaviglia/Library/Android/sdk
**Gradle task**: buildAndroidAar
**Exception**: 

`> Task :prepareAndroidBootstrap FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':prepareAndroidBootstrap'.
> java.io.FileNotFoundException: /Users/pablocaviglia/devel/projects/tool_framework_multi_platform/build/platforms/android/local.properties (No such file or directory)
`
The attached image is the structure created when the project got built from scratch (after clean task).

![image](https://user-images.githubusercontent.com/71846466/102098563-27990e00-3e06-11eb-8285-c595f6285e83.png)

The only way to make it work is to create by hand the following structure:

$project/build/platforms/android/

and by adding a valid local.properties file.

**Comment by soywiz** [comment]
Fixed here: https://github.com/korlibs/korge-next/commit/7a9f8c5dd8994400d63e5073ef97d16cdc9bd7f5
