### ISSUE TITLE
Set standard IP to 127.0.0.1 instead of 0.0.0.0

### ISSUE THREAD

**Issue by emign** [korlibs/korge-plugins#7]
On windows systems, 0.0.0.0 is unreachable with e.g. Opera and edge.

https://github.com/korlibs/korge-plugins/blob/ad82ebe5c19872ee20e6f17a5a4ee000ebc89fc9/korge-gradle-plugin/src/main/kotlin/com/soywiz/korge/gradle/KorgeExtension.kt#L131

**Comment by soywiz** [comment]
Probably better to detect 0.0.0.0 and replace to 127.0.0.1 when printing the address:
https://github.com/korlibs/korge-plugins/blob/ad82ebe5c19872ee20e6f17a5a4ee000ebc89fc9/korge-gradle-plugin/src/main/kotlin/com/soywiz/korge/gradle/HttpServerTools.kt#L32

0.0.0.0 allows to access for example from a mobile phone in your same network if you use your local network ip

**Comment by soywiz** [comment]
When `0.0.0.0` is specified:

```
> Task :jsWebRun
Listening (20410@Carloss-iMac.local-Thread[Execution worker for ':',5,main]):
  at http://192.168.1.130:60890/
  at http://127.0.0.1:60890/
```

**Comment by emign** [comment]
jsWebrun still opens 0.0.0.0 on windows which is not accessible
See here for a screencap:
https://imgur.com/13Pru3E

**Comment by soywiz** [comment]
Are you using 1.10.2.1?

**Comment by emign** [comment]
1.10.2 korge version ( I dont use the korge gradle plugin )

**Comment by soywiz** [comment]
Then where are you defining the gradle task that open the browser? If you copied it, you have to backport the fix to your project:
https://github.com/korlibs/korge-plugins/commit/4ffe993952ba3598f29b8090104c872da5fa61b5

**Comment by emign** [comment]
Sorry I wasnt thinking straight. 
I was on korgeVersion=1.10.2.0 and fixed it now. Sorry for stirring up the water
